---
title: "About"
---

## Description

This course provides graduate students with the opportunity to share their research with other students and faculty, as well as practice giving good research presentations. Each session will consist of either two short presentations or one long presentation. Presenters will receive constructive feedback from both myself and the audience, on both the presentation and research content. Students are encouraged (and expected) to contribute to discussions - this helps both the presenter and your own research!

## Logistics

-   Speakers are expected to present **in-person**. A Zoom link will be available only for students who cannot physically attend or external audience members.

-   Students presenting will invite their **PhD advisors** and **committee members** to attend.

-   All PhD students in Statistical Science are recommended to register for STA 701S each semester, and **all PhD students in Statistical Science in Years 3+** of studies will be required to register and present in STA 701S each year.

-   There will be **two talks** scheduled in each class. Each talk should be **no longer than 25 minutes**, which leaves ample time for questions & suggestions from the audience.

-   First and second year PhD students will serve as **Moderators**, who will introduce the speakers and facilitate Q&A.

-   Any students who will need to change the date of the presentation should submit a [request](https://github.com/merliseclyde/sta701-F23/issues/new/choose) in Github.[^1] Please provide the alternate date(s) and confirmation that the other individual is willing to switch.

-   Please submit [titles and abstracts](https://github.com/merliseclyde/sta701-F23/issues/new/choose) at least one week in advance.

[^1]: You must be logged in to GitHub to submit a request.
